# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: ba1a7821c2abed7c25c33bdf2da01b153cf188cbb9a95923331c7ec6c12fa32ccb5a1ddbcf6a9f1ab8d4c955396b1bf0083fa1dd805bed33d7349b5b0b9f1399

test:
  secret_key_base: d2c3260bd3f81c9559c831fe7a524043d9c8425ed774f28463733fca5dc989d4443a2259fcf0ccae1ea51195385c651a5c802ac483c23dbf381f10dbe91d5317

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
